### ISSUE TITLE
Editing seat plan makes reserved seats disappear

### ISSUE THREAD

**Issue by ankitamenon** [ChrisRuff/SWE4103_Project#103]
Steps to reproduce:

If the prof edits the seating plan by changing its dimension, all the previously reserved seats of students disappear along with all the other saved seat types.

**Comment by mrideout1** [comment]
This is expected! Since the only instance a professor would change the dimensions of a class would be to change the classroom all together, meaning the layout for seat types would likely be different anyways. @nicoleduplessis could you confirm this? (There could be something to be said about sending a notification to the student account saying they need to re reserve a seat, however if dawn mentions that we can also argue that it is the professors job to email the students to let them know this)
